### PR TITLE
Updating my fork, and finally getting my track listed.

### PR DESCRIPTION
**Pull request by PathDependence**

### CODE REVIEW

**Comment by fzipi** [comment]
@PathDependence Sadly, there are many conflicts now.

Did you saw that there are 213 changes in your PR?

**Comment by PathDependence** [comment]
> @PathDependence Sadly, there are many conflicts now.
> 
> Did you saw that there are 213 changes in your PR?

According to the GitHub interface it now stands at "This branch is 2 commits ahead, 370 commits behind OpenSecuritySummit:master.". So there's only 2 changes I want to submit, but I lost at least one evening trying to figure out how to update my copy of the repo, and then submit my two changes, as separate activities.

If there's no obvious solution I **assume** you can you close my pull request and I'll need to figure it out ;)

**Comment by DinisCruz** [comment]
Hi @PathDependence (i,e Nick) let's sync up in Slack (I can help you)

**Comment by PathDependence** [comment]
Closing this, I'll figure out how to either fix my copy of the master repo, or as Diniz suggested on Slack, delete it and start again.

**Pull request closed without merging**
